language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t anthony/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anthony/docker-react npm run test
